Webb_Shop_Weapons/Models/ShoppingCart.cs
namespace Webb_Shop_Weapons.Models
{
    public class ShoppingCart
    {
        public int ShoppingCartId { get; set; }
        public int AccountId { get; set; }
        public Account Account { get; set; }
        public ICollection<CartItem> Items { get; set; }
    }
}

Webb_Shop_Weapons/Pages/Checkout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using Webb_Shop_Weapons.Data;
using Webb_Shop_Weapons.Models;

namespace Webb_Shop_Weapons.Pages
{
    public class CheckoutModel : PageModel
    {
        private readonly AppDbContext _database;
        private readonly AccessControl _accessControl;

        public ShoppingCart ShoppingCart { get; set; }
        public decimal TotalPrice { get; private set; }

        public CheckoutModel(AppDbContext database, AccessControl accessControl)
        {
            _database = database;
            _accessControl = accessControl;
        }

        public IActionResult OnGet()
        {
            var currentUser = _database.Accounts.FirstOrDefault(a => a.ID == _accessControl.LoggedInAccountID);
            if (currentUser == null)
            {
                return RedirectToPage("/Index"); 
            }

            ShoppingCart = LoadUserShoppingCart(currentUser.ID);
            TotalPrice = ShoppingCart?.Items.Sum(i => i.Quantity * i.Product.Price) ?? 0;
            Console.WriteLine(TotalPrice);

            return Page(); 
        }

        private ShoppingCart LoadUserShoppingCart(int userId)
        {
            
            return _database.ShoppingCarts
                            .Include(cart => cart.Items)
                            .ThenInclude(item => item.Product)
                            .FirstOrDefault(cart => cart.AccountId == userId);
        }
    }
}

Webb_Shop_Weapons/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Webb_Shop_Weapons.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Webb_Shop_Weapons/Pages/FakeLogin.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using Webb_Shop_Weapons.Data;

namespace Webb_Shop_Weapons.Pages
{
    public class FakeLoginModel : PageModel
    {
        private readonly AppDbContext database;
        private readonly IWebHostEnvironment environment;

        public FakeLoginModel(AppDbContext database, IWebHostEnvironment environment)
        {
            this.database = database;
            this.environment = environment;
        }

        // Log in as the user with the specified account ID, without providing a password etc.
        // IMPORTANT: This should only be allowed in development, hence the if statement below.
        public async Task<IActionResult> OnPost(int accountID)
        {
            if (!environment.IsDevelopment())
            {
                return Forbid();
            }

            // Find the account in the database.
            var account = database.Accounts.Find(accountID);
            string subject = account.OpenIDSubject;
            string issuer = account.OpenIDIssuer;
            string name = account.Name;

            // Create the fake identity and principal objects needed to fake a login.
            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, subject, valueType: null, subject: identity, issuer: issuer, originalIssuer: null));
            identity.AddClaim(new Claim(ClaimTypes.Name, name, valueType: null, subject: identity, issuer: issuer, originalIssuer: null));
            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(principal);

            return RedirectToPage("./Index");
        }
    }
}

Webb_Shop_Weapons/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;
using System.Security.Cryptography.X509Certificates;
using Webb_Shop_Weapons.Data;
using Webb_Shop_Weapons.Models;

namespace Webb_Shop_Weapons.Pages
{
    public class IndexModel : PageModel
    {
        private readonly AppDbContext database;
        private readonly AccessControl accessControl;
        public List<Weapon> weapons { get; set; } = new List<Weapon>();
        private const int PageSize = 10;
        public ShoppingCart shoppingCart { get; set; }

        public IndexModel(AppDbContext database, AccessControl accessControl)
        {
            this.database = database;
            this.accessControl = accessControl;
        }

        public IList<Weapon> Weapons { get; set; }
        public int CurrentPage { get; set; }
        public bool HasNextPage { get; set; }
        public bool HasPreviousPage { get; set; }
        public string SearchBar { get; set; }
        public string CategorySelect { get; set; }


        public IActionResult OnGet(int pageID = 0, string? searchBar = null, string? category = null)
        {
            CurrentPage = pageID;
            SearchBar = searchBar;
            CategorySelect = category;

            IQueryable<Weapon> weaponsearch = database.Weapons;

            if (!string.IsNullOrEmpty(CategorySelect) && CategorySelect != "All")
            {
                weaponsearch = weaponsearch.Where(weapon => weapon.Category.Name == CategorySelect);
            }

            if (!string.IsNullOrEmpty(SearchBar))
            {
                weaponsearch = weaponsearch.Where(weapon => weapon.Name.Contains(SearchBar));
            }
            
            var totalCount = weaponsearch.Count();
            var totalPages = (int)Math.Ceiling(totalCount / (double)PageSize);

            Weapons = weaponsearch
                .OrderBy(weapon => weapon.Name)
                .Skip((CurrentPage) * PageSize)
                .Take(PageSize)
                .ToList();

            HasNextPage = CurrentPage < totalPages - 1; 
            HasPreviousPage = CurrentPage > 0;

            return Page();

            
        }



        public IActionResult OnPostAddToCart(int productId)
        {
            var currentUser = database.Accounts.FirstOrDefault(a => a.ID == accessControl.LoggedInAccountID);
            if (currentUser == null)
            {
                return RedirectToPage("index");
            }

            shoppingCart = LoadUserShoppingCart(currentUser.ID);


            if (shoppingCart == null)
            {
                shoppingCart = new ShoppingCart { AccountId = currentUser.ID };
                database.ShoppingCarts.Add(shoppingCart);
            }


            var item = shoppingCart.Items.FirstOrDefault(i => i.Product.ProductId == productId);

            if (item != null)
            {

                item.Quantity += 1;
            }
            else
            {

                var newItem = new CartItem
                {
                    ProductId = productId,
                    Quantity = 1,
                    ShoppingCartId = shoppingCart.ShoppingCartId
                };
                shoppingCart.Items.Add(newItem);
            }


            database.SaveChanges();

            var product = database.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                TempData["Message"] = $"{product.Name} has been added to your cart.";
            }
            return RedirectToPage();
        }

        public ShoppingCart LoadUserShoppingCart(int userId)
        {
            var shoppingCart = database.ShoppingCarts
                           .FirstOrDefault(cart => cart.AccountId == userId);

            if (shoppingCart != null)
            {
                shoppingCart = database.ShoppingCarts
                           .Include(cart => cart.Items)
                           .ThenInclude(item => item.Product)
                           .FirstOrDefault(cart => cart.AccountId == userId);
            }

            return shoppingCart;
        }




    }
}

Webb_Shop_Weapons/Pages/Checkout.cshtml
@page
@model Webb_Shop_Weapons.Pages.CheckoutModel
@inject Webb_Shop_Weapons.Data.AccessControl accessControl


@{
    ViewData["Title"] = "Checkout Summary";
}
<head>
    <link rel="stylesheet" href="~/css/cart.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<div class="WeaponCard">
<h1>Checkout Summary:</h1>
<h3>Thanks For your order!</h3>
@if (Model.ShoppingCart != null && Model.ShoppingCart.Items.Any())
{
        <h2>Total Price: $@Model.TotalPrice.ToString("N2")</h2>
}
else
{
    <p>Your shopping cart is empty.</p>
}
<form class="back-home" method="get" asp-page="/index">
    <button type="submit" class="dltbtn">Back to store!</button>
</form>

</div>

Webb_Shop_Weapons/Pages/FakeLogin.cshtml
@page
@model Webb_Shop_Weapons.Pages.FakeLoginModel
@{
}

Webb_Shop_Weapons/Pages/Index.cshtml
@page
@model IndexModel
@inject Webb_Shop_Weapons.Data.AccessControl accessControl
@{
    ViewData["Title"] = "Home page";
}

<head>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<div class="top">
    <div class="filter">
        <form class ="searchbar">
            <button class="searchbtn"><i class="fa-solid fa-magnifying-glass" style="color: #ffffff;"></i></button>
            <input type="text" name="searchBar" class="searchBar" />
            <select name="category" class="dropdown">
                <option value="All">Category</option>
                <option value="Assault Rifle">Assault Rifle</option>
                <option value="Pistol">Pistol</option>
                <option value="Sniper Rifle">Sniper Rifle</option>
                <option value="Melee Weapon">Melee Weapon</option>
                <option value="Machine gun">Machine gun</option>
                <option value="Rocket Launcher">Rocket Launcher</option>
                <option value="Grenade Launcher">Grenade Launcher</option>
            </select>
        </form>
     </div>
    <img src="/Pictures/Images/scumborder.png" class="banner">
</div>

<div class="products">


@foreach (var weapon in Model.Weapons)
{
    <div class="productcard">
        <h2><a asp-page="/WeaponInfo" asp-route-id="@weapon.ProductId">@weapon.Name</a></h2>
        <h3>@weapon.Category</h3>
        <p>@weapon.Price</p>
            <a asp-page="/WeaponInfo" asp-route-id="@weapon.ProductId"><img src="/Pictures/Vapen/Rifle/@weapon.Image" class="weaponpic" /></a>
        <form method="post" asp-page-handler="AddToCart">
            <input type="hidden" name="productId" value="@weapon.ProductId" />
            <button type="submit" class="cartbtn"><i class="fa-solid fa-cart-shopping fa-lg"></i></button>
        </form>
    </div>
}
</div>
<form asp-page="" method="get" class="btnform">
    <button type="submit" class="btn" name="pageID" value="@(Model.CurrentPage - 1)" @if (!Model.HasPreviousPage)
    {
        <text>disabled</text>
    }>Prev</button>
    <button type="submit" class="btn" name="pageID" value="@(Model.CurrentPage + 1)" @if (!Model.HasNextPage)
    {
        <text>disabled</text>
    }>Next</button>

</form>

Webb_Shop_Weapons/Pages/ShoppingCart.cshtml
@page
@inject Webb_Shop_Weapons.Data.AccessControl accessControl
@model Webb_Shop_Weapons.Pages.ShoppingCartModel
@{
}
@{
    ViewData["Title"] = "Shopping Cart";
}

<head>
    <link rel="stylesheet" href="~/css/cart.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<img src="/Pictures/Images/scumborder.png" class="banner">

@{
    decimal totalPrice = 0;
    foreach(var i in Model.shoppingCart.Items)
    {
        totalPrice += i.Product.Price * i.Quantity;
    }
}
<div class="WeaponCard">
    @if (Model.shoppingCart != null && Model.shoppingCart.Items.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Total</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.shoppingCart.Items)
                {
                    <tr>
                        <td>@item.Product.Name</td>
                        <td>
                            <form method="post">
                                <input type="hidden" name="productId" value="@item.Product.ProductId" />
                                <input type="number" name="quantity" value="@item.Quantity" min="1" class="quantity"/>
                                <!--Använder formaction här, då hittar den OnPost, med handler=UpdateQuantity som går att hitta i cs filen-->
                                <!--kan testa med form-page-handler med-->
                                <button type="submit" formaction="ShoppingCart?handler=UpdateQuantity" class="shopbtn">Update</button>
                            </form>
                        </td>
                        <td>$@item.Product.Price</td>
                        <td>$@(item.Product.Price * item.Quantity)</td>
                        <td>
                            <form method="post">
                                <input type="hidden" name="productId" value="@item.Product.ProductId"/>
                                <!--Samma här fast med DeleteItem-->
                                <button type="submit" formaction="ShoppingCart?handler=DeleteItem" class="shopbtn">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <h4 class="total">@totalPrice</h4>
        <form method="post">
            <button type="submit" formaction="ShoppingCart?handler=DeleteAll" class="dltbtn">Delete All</button>
        </form>

        <form method="get" asp-page="/Checkout">
            <button type="submit" class="dltbtn">CheckOut</button>
        </form>
    }
    else
    {
        <p>Your shopping cart is empty.</p>
    }
</div>

Webb_Shop_Weapons/Pages/WeaponInfo.cshtml
@page
@inject Webb_Shop_Weapons.Data.AccessControl accessControl
@model Webb_Shop_Weapons.Pages.WeaponInfoModel
@{
    ViewData["Title"] = "Weapon Info";
}

<head>
    <link rel="stylesheet" href="~/css/weaponinfo.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<img src="/Pictures/Images/scumborder.png" class="banner">


<div class="WeaponCard">
        <h2>@Model.Weapon.Name</h2>

        <h3>@Model.Weapon.Category.Name</h3>
        @if(Model.Weapon.AmmoId != null){
        <h3>@Model.Weapon.Ammo.Name</h3>
        }
        <p>@Model.Weapon.Price</p>
        <img src="/Pictures/Vapen/Rifle/@Model.Weapon.Image" class="weaponpic" />
    <form method="post" asp-page-handler="AddToCart" class="AddToCart">
        <input type="number" name="quantity" class="quantity" value="1" />
        <input type="hidden" name="productId" value="@Model.Weapon.ProductId" />
        <!--Behövs för att skicka tillbaka till rätt vapen när man köper ammo-->
        <input type="hidden" name="viewingWeaponId" value="@Model.Weapon.ProductId" />
        <button type="submit" class="addtocartbtn">Add to cart</button>
    </form>
        <h4 class="description">@Model.Weapon.Description</h4>
</div>
@if(Model.Weapon.AmmoId != null){
<div class="AmmoCard">
      <h2>Fitting Ammo</h2>
      <h3>@Model.Weapon.Ammo.Name</h3>
      <h4>@Model.Weapon.Ammo.Description</h4>
      <p>@Model.Weapon.Ammo.Price</p>
      <img src="/Pictures/Ammo/@Model.Ammo.Image" class="ammopic"/>
      <form method="post" asp-page-handler="AddToCart" class="AddToCart">
                <input type="number" name="Quantity" class="quantity" value="1" />
                <input type="hidden" name="productId" value="@Model.Ammo.ProductId" />
            <!--Behövs för att skicka tillbaka till rätt vapen när man köper ammo, blir att den försöker ladda på ammo annars, blir null-->
                <input type="hidden" name="viewingWeaponId" value="@Model.Weapon.ProductId" />
                <button type="submit" class="addtocartbtn">Add to cart</button>
            </form>
</div>
}